title: lppt home

email: i@lppt.ru
description: >- # this means to ignore newlines until "baseurl:"
  no description here
baseurl: ""
url: "https://lppt.ru"
twitter_username: lppt
github_username:  lppt

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed